name: Lint, Build, and Dockerize

on:
  push:
    branches:
      - main
      - ci/**

  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    env:
      BETTER_AUTH_SECRET: dummysecret123
      MICROSOFT_CLIENT_ID: dummyclientid
      MICROSOFT_CLIENT_SECRET: dummyclientsecret

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

  dockerize:
    needs: lint-build
    runs-on: ubuntu-latest
    env:
      BETTER_AUTH_SECRET: dummysecret123
      MICROSOFT_CLIENT_ID: dummyclientid
      MICROSOFT_CLIENT_SECRET: dummyclientsecret

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t nextjs-better-auth:latest .
